var greet="Good Morning virat Dude";
var lengthgreet=greet.length;
console.log('leanth of String=',lengthgreet);
var charat=greet.charAt(0);
console.log(`${greet} - Char at 0th Index  ${charat}`);
var lastindex=greet.charAt(lengthgreet-1);
console.log(`${greet}- Last char at ${lastindex} index is ${lengthgreet}`);
console.log("------------------------------------------------------------------------------------------------------------");
var firstName="Prafull";
var lastName=" Pailwan";
var result=firstName.concat(lastName);
console.log(`Concat String- ${result}`);
console.log("------------------------------------------------------------------------------------------------------------");
console.log(greet.indexOf('o'));
var result=greet.indexOf('ing');
console.log(`Index of sub string is ${result}`);

console.log("------------------------------------------------------------------------------------------------------------");
var result=greet.includes('virat');
console.log(`Result is ${result}`);
console.log("------------------------------------------------------------------------------------------------------------");
result=greet.split(' ');
console.log(`S plied string is : ${result}  Total of words are- ${result.length}`);
console.log("------------------------------------------------------------------------------------------------------------");
var greet="           Good Morning         ";
result=greet.trim();
console.log(`Before trimed length is ${greet.length} After Trimed string is: ${result} and its length is ${result.length}`);
result=greet.trimEnd();
var trimEndLength=result.length;
var re=greet.length-trimEndLength;
console.log(`TrimEnd: ${result} and length is:${result.length} and Removing Space is:${re}`);
console.log("------------------------------------------------------------------------------------------------------------");
greet="Good Morning";
result=greet.replace(' ','-');
console.log(`After Replase ' ' with '-' String is:${result}`);
console.log("------------------------------------------------------------------------------------------------------------");
greet="Good Morning Virat Dude";
result=greet.slice(5,12);
console.log(`Slice String From index 5 till 12 is: ${result}`);